from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

# Consolidate the shared runtime CSS so every tool needs one shared stylesheet
# instead of four/five separate render-blocking requests.
shared_parts = [
    ROOT / 'assets/css/platform.css',
    ROOT / 'assets/css/home-parity.css',
    ROOT / 'assets/css/design-system.css',
    ROOT / 'assets/css/design-taste.css',
]
offer_parts = [
    ROOT / 'assets/css/platform.css',
    ROOT / 'assets/css/home-parity.css',
    ROOT / 'assets/css/offer-mobile.css',
    ROOT / 'assets/css/design-system.css',
    ROOT / 'assets/css/design-taste.css',
]

def bundle(paths, label):
    return f'/* {label} — generated by performance pass. */\n' + '\n'.join(p.read_text(encoding='utf-8') for p in paths)

(ROOT / 'assets/css/tool-runtime.css').write_text(bundle(shared_parts, 'Shared tool runtime'), encoding='utf-8')
(ROOT / 'assets/css/offer-runtime.css').write_text(bundle(offer_parts, 'Offer runtime'), encoding='utf-8')

pages = [
    'json-formatter/index.html',
    'loan-calculator/index.html',
    'qr-generator/index.html',
    'stock-analysis-dashboard/index.html',
    'time/index.html',
    'wheel-of-names/index.html',
]
shared_hrefs = [
    '/assets/css/platform.css',
    '/assets/css/home-parity.css',
    '/assets/css/design-system.css',
    '/assets/css/design-taste.css',
]

def remove_css_link(html, href):
    return re.sub(rf'\s*<link[^>]+href=["\']{re.escape(href)}(?:\?[^"\']*)?["\'][^>]*>', '', html, flags=re.I)

for rel in pages:
    path = ROOT / rel
    html = path.read_text(encoding='utf-8')
    for href in shared_hrefs:
        html = remove_css_link(html, href)
    if '/assets/css/tool-runtime.css' not in html:
        html = html.replace('</head>', '<link rel="stylesheet" href="/assets/css/tool-runtime.css">\n</head>', 1)
    path.write_text(html, encoding='utf-8')

# Offer gets an exact-order bundle including its mobile compatibility layer.
offer_path = ROOT / 'offer/index.html'
offer_html = offer_path.read_text(encoding='utf-8')
for href in shared_hrefs + ['/assets/css/offer-mobile.css']:
    offer_html = remove_css_link(offer_html, href)
offer_html = re.sub(r'\s*<script[^>]+src=["\']https://cdnjs\.cloudflare\.com/ajax/libs/xlsx/0\.18\.5/xlsx\.full\.min\.js["\'][^>]*></script>', '', offer_html, flags=re.I)
offer_html = re.sub(r'\s*<meta\s+http-equiv=["\']Cache-Control["\'][^>]*>', '', offer_html, flags=re.I)
offer_html = re.sub(r'\s*<meta\s+http-equiv=["\']Pragma["\'][^>]*>', '', offer_html, flags=re.I)
if '/assets/css/offer-runtime.css' not in offer_html:
    offer_html = offer_html.replace('</head>', '<link rel="stylesheet" href="/assets/css/offer-runtime.css">\n</head>', 1)
offer_path.write_text(offer_html, encoding='utf-8')

offer_js_path = ROOT / 'assets/js/pages/offer.js'
offer_js = offer_js_path.read_text(encoding='utf-8')
if 'ensureXlsxLibrary' not in offer_js:
    old = "function exportExcel() {\n  const wb = XLSX.utils.book_new();"
    new = """let xlsxLibraryPromise;
function ensureXlsxLibrary() {
  if (window.XLSX) return Promise.resolve(window.XLSX);
  if (!xlsxLibraryPromise) {
    xlsxLibraryPromise = new Promise((resolve, reject) => {
      const script = document.createElement('script');
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';
      script.async = true;
      script.onload = () => resolve(window.XLSX);
      script.onerror = () => reject(new Error('Failed to load Excel export library'));
      document.head.appendChild(script);
    });
  }
  return xlsxLibraryPromise;
}
async function exportExcel() {
  try { await ensureXlsxLibrary(); }
  catch (_) { alert(currentLang === 'ar' ? 'تعذر تحميل مكتبة تصدير Excel.' : 'Could not load the Excel export library.'); return; }
  const wb = XLSX.utils.book_new();"""
    if old not in offer_js:
        raise SystemExit('Offer export marker not found')
    offer_js = offer_js.replace(old, new, 1)
offer_js_path.write_text(offer_js, encoding='utf-8')

# QR library: load only when a QR is actually rendered.
qr_html_path = ROOT / 'qr-generator/index.html'
qr_html = qr_html_path.read_text(encoding='utf-8')
qr_html = re.sub(r'<script[^>]+src=["\']https://cdn\.jsdelivr\.net/npm/qrcodejs@1\.0\.0/qrcode\.min\.js["\'][^>]*></script>', '', qr_html, flags=re.I)
qr_html_path.write_text(qr_html, encoding='utf-8')

qr_js_path = ROOT / 'assets/js/pages/qr-generator.js'
qr_js = qr_js_path.read_text(encoding='utf-8')
if 'ensureQrLibrary' not in qr_js:
    marker = "function qrAvailable(){return typeof window.QRCode==='function'}"
    loader = """let qrLibraryPromise;
function qrAvailable(){return typeof window.QRCode==='function'}
function ensureQrLibrary(){if(qrAvailable())return Promise.resolve(window.QRCode);if(!qrLibraryPromise){qrLibraryPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js';s.async=true;s.onload=()=>qrAvailable()?resolve(window.QRCode):reject(new Error('QR library unavailable'));s.onerror=()=>reject(new Error('QR library unavailable'));document.head.appendChild(s)})}return qrLibraryPromise}"""
    if marker not in qr_js:
        raise SystemExit('QR availability marker not found')
    qr_js = qr_js.replace(marker, loader, 1)
    old_render = "function renderValue(showSuccess=true){statusEl.classList.remove('error');const value=getPayload();if(!value){statusEl.textContent=currentMode==='contact'?STRINGS[currentLang].contactEmpty:STRINGS[currentLang].empty;statusEl.classList.add('error');clearQr();return false}try{drawQr(value);if(showSuccess)statusEl.textContent=currentMode==='contact'?STRINGS[currentLang].contactOk:STRINGS[currentLang].ok;return true}catch(err){console.error('QR render failed',err);clearQr();statusEl.textContent=qrAvailable()?STRINGS[currentLang].renderFail:STRINGS[currentLang].libraryFail;statusEl.classList.add('error');return false}}"
    new_render = "function renderValue(showSuccess=true){statusEl.classList.remove('error');const value=getPayload();if(!value){statusEl.textContent=currentMode==='contact'?STRINGS[currentLang].contactEmpty:STRINGS[currentLang].empty;statusEl.classList.add('error');clearQr();return Promise.resolve(false)}return ensureQrLibrary().then(()=>{drawQr(value);if(showSuccess)statusEl.textContent=currentMode==='contact'?STRINGS[currentLang].contactOk:STRINGS[currentLang].ok;return true}).catch(err=>{console.error('QR render failed',err);clearQr();statusEl.textContent=qrAvailable()?STRINGS[currentLang].renderFail:STRINGS[currentLang].libraryFail;statusEl.classList.add('error');return false})}"
    if old_render not in qr_js:
        raise SystemExit('QR render marker not found')
    qr_js = qr_js.replace(old_render, new_render, 1)
    qr_js = qr_js.replace("function generate(){renderValue(true)}", "async function generate(){await renderValue(true)}", 1)
    old_download = "function download(){if(!renderValue(false))return;const canvas=output.querySelector('canvas'),img=output.querySelector('img'),a=document.createElement('a');a.href=canvas?canvas.toDataURL('image/png'):img?.src;if(!a.href)return;a.download=`${currentMode==='contact'?'vcard':'qr'}-${new Date().toISOString().slice(0,10)}.png`;document.body.append(a);a.click();a.remove();statusEl.textContent=STRINGS[currentLang].downloaded}"
    new_download = "async function download(){if(!await renderValue(false))return;const canvas=output.querySelector('canvas'),img=output.querySelector('img'),a=document.createElement('a');a.href=canvas?canvas.toDataURL('image/png'):img?.src;if(!a.href)return;a.download=`${currentMode==='contact'?'vcard':'qr'}-${new Date().toISOString().slice(0,10)}.png`;document.body.append(a);a.click();a.remove();statusEl.textContent=STRINGS[currentLang].downloaded}"
    if old_download not in qr_js:
        raise SystemExit('QR download marker not found')
    qr_js = qr_js.replace(old_download, new_download, 1)
qr_js_path.write_text(qr_js, encoding='utf-8')

# Stock dashboard: no chart library, market requests, trending fan-out, or AI request on first paint.
stock_html_path = ROOT / 'stock-analysis-dashboard/index.html'
stock_html = stock_html_path.read_text(encoding='utf-8')
stock_html = re.sub(r'\s*<script[^>]+src=["\']https://unpkg\.com/lightweight-charts/dist/lightweight-charts\.standalone\.production\.js["\'][^>]*></script>', '', stock_html, flags=re.I)
stock_html_path.write_text(stock_html, encoding='utf-8')

stock_js_path = ROOT / 'assets/js/pages/stock-analysis-dashboard.js'
stock_js = stock_js_path.read_text(encoding='utf-8')
if 'ensureChartLibrary' not in stock_js:
    marker = "const YAHOO_BASE = 'https://query1.finance.yahoo.com';"
    loader = """const YAHOO_BASE = 'https://query1.finance.yahoo.com';
const CHART_LIB_URL = 'https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js';
let chartLibraryPromise;
function ensureChartLibrary(){if(window.LightweightCharts)return Promise.resolve(window.LightweightCharts);if(!chartLibraryPromise){chartLibraryPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=CHART_LIB_URL;s.async=true;s.onload=()=>window.LightweightCharts?resolve(window.LightweightCharts):reject(new Error('Chart library unavailable'));s.onerror=()=>reject(new Error('Chart library unavailable'));document.head.appendChild(s)})}return chartLibraryPromise}"""
    if marker not in stock_js:
        raise SystemExit('Stock YAHOO marker not found')
    stock_js = stock_js.replace(marker, loader, 1)
    old_draw = "function drawChart(payload){\n  if(!payload?.candles?.length) return;\n  chartDataCache = payload;\n  if(!chartVisible) return;\n  initChart();"
    new_draw = "async function drawChart(payload){\n  if(!payload?.candles?.length) return;\n  chartDataCache = payload;\n  if(!chartVisible) return;\n  await ensureChartLibrary();\n  initChart();"
    if old_draw not in stock_js:
        raise SystemExit('Stock drawChart marker not found')
    stock_js = stock_js.replace(old_draw, new_draw, 1)
    stock_js = stock_js.replace("    drawChart({ candles, sma10, sma50, sma200, volume: volumeData });", "    await drawChart({ candles, sma10, sma50, sma200, volume: volumeData });", 1)
    old_boot = "document.getElementById('tickerInput').value = '7202';\napplyTheme(currentTheme);\napplyLanguage(currentLang);\nsetupChartVisibility();\nrenderFavorites();\nrenderTrending();\nanalyzeTicker('7202');"
    new_boot = """document.getElementById('tickerInput').value = '7202';
applyTheme(currentTheme);
applyLanguage(currentLang);
setupChartVisibility();
renderFavorites();
document.getElementById('trendingList').innerHTML = '<div class=\"muted\">—</div>';
let trendingLoaded = false;
function loadTrendingOnDemand(){if(trendingLoaded)return;trendingLoaded=true;renderTrending()}
window.addEventListener('scroll', loadTrendingOnDemand, {once:true,passive:true});"""
    if old_boot not in stock_js:
        raise SystemExit('Stock bootstrap marker not found')
    stock_js = stock_js.replace(old_boot, new_boot, 1)
stock_js_path.write_text(stock_js, encoding='utf-8')

print('Phase 2 performance optimizations applied.')
